import type { Metadata } from 'next';
import '@/app/globals.css';
import AdSidebar from '@/components/sidebar/AdSidebar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export async function generateStaticParams() {
    return [{ lang: 'en' }, { lang: 'vi' }];
}

type Props = Readonly<{
    children: React.ReactNode;
    params: { lang: string };
}>;

export default async function Layout({ children, params }: Props) {
    return (
        <div className="flex h-screen bg-slate-100">
            <AdSidebar />
            <div className="flex-1 mx-4">
                {children}
            </div>
        </div>
    );
}
