import type { Metadata } from 'next';
import '@/app/globals.css';
import RcSidebar from '@/components/sidebar/RcSidebar';
import RootLayout from '@/app/layout';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export async function generateStaticParams() {
    return [{ lang: 'en' }, { lang: 'vi' }];
}

type Props = Readonly<{
    children: React.ReactNode;
    params: { lang: string };
}>;

export default async function Layout({ children, params }: Props) {
    return (
        // eslint-disable-next-line react/no-children-prop
        <RootLayout children={
            <div className="flex">
                <RcSidebar />
                <div className="flex-1 px-2 py-2 bg-white lg:p-6">
                    {children}
                </div>
            </div>
        } params={params}/>
    );
}
