import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Provider from '@/context/Provider';
import { auth } from '@/auth';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import StoreProvider from './StoreProvider';
import ModalLoader from '@/components/loader/ModalLoader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
        <StoreProvider>
          {children}
          <ModalLoader />
        </StoreProvider>
      </body>
    </html>
  );
}
