import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import Provider from '@/context/Provider';
import { auth } from '@/auth';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { useSession } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'vi' }];
}

type Props = Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>;

export default async function RootLayout({ children, params }: Props) {
  const session = await auth()
  const messages = await getMessages()
  console.log("Layout FIle: ", params.lang);
  
  return (
    <html lang={params.lang}>
      <Provider session={session}>
        <NextIntlClientProvider messages={messages} locale={params.lang}>
          <body className={inter.className}>{children}</body>
        </NextIntlClientProvider>
      </Provider>
    </html>
  );
}
