import type { Metadata } from 'next';
import '@/app/globals.css';
import JsSidebar from '@/components/sidebar/JsSidebar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export async function generateStaticParams() {
    return [{ lang: 'en' }, { lang: 'vi' }];
}

type Props = Readonly<{
    children: React.ReactNode;
    params: { lang: string };
}>;

export default async function Layout({ children, params }: Props) {
    return (
        <div className="flex">
            <JsSidebar />
            <div className="px-6 py-10 sm:px-8 xl:px-14 grow">
                {children}
            </div>
        </div>
    );
}
