import type { Metadata } from 'next';
import '@/app/globals.css';
import { getSession } from 'next-auth/react';
import RHeadder from '@/components/header/RHeader';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export async function generateStaticParams() {
    return [{ lang: 'en' }, { lang: 'vi' }];
}

type Props = Readonly<{
    children: React.ReactNode;
    params: { lang: string };
}>;

export default async function Layout({ children, params }: Props) {
    const session = await getSession()
    return (
        <div>
            { session?.user.role == "Recruiter" && <RHeadder/> }
            { children }
        </div>
    )
}
